### ISSUE TITLE
Mejorar indexado de DB

### ISSUE THREAD

**Issue by gianpietro1** [openpolitica/open-politica-backend#47]
En base a estas queries:
https://github.com/openpolitica/open-politica-backend/tree/develop/src/services

**Comment by SergioBerrospi** [comment]
Gianpietro, viendo el reset_mysql.sh pienso que se debería cambiar esta parte 

`ALTER TABLE data_ec ADD INDEX (designado, inmuebles_total, muebles_total, deuda_sunat, aportes_electorales, procesos_electorales_participados, procesos_electorales_ganados, papeletas_sat, sancion_servir_registro);`

a esto

`ALTER TABLE data_ec ADD INDEX (hoja_vida_id, designado, inmuebles_total, muebles_total, deuda_sunat, aportes_electorales, procesos_electorales_participados, procesos_electorales_ganados, papeletas_sat, sancion_servir_registro);`
