### ISSUE TITLE
votu_backend debe reconectarse a mariadb en caso arranque primero

### ISSUE THREAD

**Issue by gianpietro1** [openpolitica/open-politica-backend#58]
@dmarquinah debemos implementar reconexiones porque ahora backend y mariadb comparten el mismo docker-compose, y creo que no hay manera de forzar que uno arranque primero; podemos tomar el ejemplo de lo que teníamos en mongo.

**Comment by dmarquinah** [comment]
Osea se requeriría que primero se haga build del BD y luego del backend, en ese orden?

**Comment by dmarquinah** [comment]
Podemos probar con este statement para [docker-compose](https://docs.docker.com/compose/startup-order/)

**Comment by gianpietro1** [comment]
faltaba eso y el `restart: always` en la DB, a probar de nuevo!

**Comment by gianpietro1** [comment]
@dmarquinah como conversamos, aquí haría falta reconectarnos como lo hacíamos en MongoDB
