### ISSUE TITLE
Contador de respuestas de vacancia

### ISSUE THREAD

**Issue by gianpietro1** [openpolitica/open-politica-backend#66]
Se requiere implementar un contador de la respuesta de vacancia, podemos aprovechar el write por región, es decir, dos nuevas columnas si_vacancia, no_vacancia que vayan contando cuál fue la respuesta en cada caso.
@dmarquinah podrías tomarlo?

**Comment by gianpietro1** [comment]
@dmarquinah luego de hacer el merge, me di cuenta de que no funciona el vacancia "true", creo que frontend manda true o "nada" (nunca false), puedes darle una mirada?

**Comment by dmarquinah** [comment]
@gianpietro1 he creado un PR aparte para solucionar este problema: [Link al PR](https://github.com/openpolitica/open-politica-backend/pull/94)
